### ISSUE TITLE
Help (Updating PS4GENTOO)

### ISSUE THREAD

**Issue by gabriel-maxx** [Richard-Rogalski/ps4-overlay#1]
hello i would like to know how do i update gentoo on my ps4 with this updated overlay ? Could you explain step by step please?

**Comment by rrrogalski** [comment]
Of course! 

So, I'm assuming you want to update Mircoho's PS4Gentoo, and not your own install?

If so, things will get, complicated. PS4Gentoo was released a relatively long time ago, in a profile no longer supported by upstream gentoo. I myself haven't done this, and am not near my ps4 right now, but I imagine these would be the steps, although I might be missing some.

Note that upgrading gentoo more than a year old is unsupported and there is no good way to do it. It might be easier to do a new install, but that needs a bit of pre existing linux knowledge. There are 3 good resources online for updating an ancient gentoo install, I'll walk through the third as that seems the smartest and most sane.  
https://wiki.gentoo.org/wiki/User:NeddySeagoon/HOWTO_Update_Old_Gentoo  
https://forums.gentoo.org/viewtopic-t-1104292-highlight-.html  
https://wiki.gentoo.org/wiki/Upgrading_Gentoo#Updating_old_systems  

First, type either `su` or `sudo su` to become the root user in a terminal :)

Second, run `eselect profile list`, find the one that only has /systemd after the version number, or that has /desktop/plasma/systemd if it is available. Take the number that is to the left of that profile and then run `eselect profile set whateverthenumberis`. 

Next, go to this website <https://www.gentoo.org/downloads/>, and download the latest stage3 tarball for amd64 that says systemd. Then, run these commands as root:
```
mkdir -p /mnt/build
tar -xf /home/user/Downloads/stage3*.tar.xz -C /mnt/build
mount --rbind /dev /mnt/build/dev
mount --rbind /proc /mnt/build/proc
mount --rbind /sys /mnt/build/sys 
mkdir -p /mnt/build/mnt/host
mount --rbind / /mnt/build/mnt/host 
cp -L /etc/resolv.conf /mnt/build/etc/
```
Replace /home/user/Downloads with wherever you downloaded the tarball.  
Now, we will begin the update procedure:
```
chroot /mnt/build 
source /etc/profile  

emerge --sync
emerge --root=/mnt/host --config-root=/mnt/host --verbose --oneshot sys-apps/portage
emerge --root=/mnt/host --config-root=/mnt/host --verbose --oneshot --keep-going --deep --update --changed-use sys-apps/portage
emerge --root=/mnt/host --config-root=/mnt/host --update --newuse --deep --ask --keep-going @system
emerge --root=/mnt/host --config-root=/mnt/host --update --newuse --deep --ask --keep-going @world
```
Some packages might give you problems. For example, let's say the mesa package. Try appending `--exclude="mesa"` to the end of one of the update commands, and replace mesa with the names of any package causing potential problems. We can deal with those packages later.  

Some USE flag changes might also need to be applied. Open /etc/portage/package.use in a text editor and it should be self explanatory. Each line starts with the name of the package, then after that what flags to enable in the software, and if they begin with a `-` then that tells your system to disable that flag. Edit that file with the changes portage will probably tell you to do. It is alright if not every package gets updated, just try to get as many updated as possible. Adding my overlay in the next step should hopefully fix some of these problems.  

*Assuming* that went well, you should install this repository! Edit the file in /etc/portage/repos.conf/ whose name is something like ps4-overlay.conf. There should be a URL in that file, change that to the URL of this repository. Then, in a **new terminal** run `emerge --sync ps4-overlay`, or maybe it was just `emerge --sync ps4`. Then, run these commands to update your system for the last time with the proper overlay **still in the new terminal**.  
(note, it may just be ps4 instead of ps4-overlay)
```
emerge --update --deep --newuse --keep-going --ask -v mesa::ps4-overlay xf86-video-amdgpu::ps4-overlay libdrm::ps4-overlay
emerge --update --deep --newuse --keep-going --ask -v @world
```
And that should be it! Let me know how it goes, I could be missing some steps.

**Comment by rrrogalski** [comment]
Actually in retrospect, it may be smarter to add this overlay first. Skip to the paragraph that starts in *Assuming* and do that. The update commands after that paragraph are unlikely to get anywhere, so just follow the instructions from the beginning after you add the overlay.

**Comment by gabriel-maxx** [comment]
> 
> ```
> emerge --update --deep --newuse --keep-going --ask -v mesa::ps4-overlay xf86-video-amdgpu::ps4-overlay libdrm::ps4-overlay
> emerge --update --deep --newuse --keep-going --ask -v @world
> ```
> 
thanks I'll try it tomorrow, just a doubt these two commands will install the ps4 fan control too?

**Comment by rrrogalski** [comment]
Mesa, libdrm, and xf86-video-amdgpu are already installed on PS4Gentoo, the goal of that command was to update them with the PS4 specific patches. Many other programs depend on these programs so updating them is important. 

You can install ps4fancontrol after installing this repository with a simple
`emerge ps4fancontrol`. The instructions for ps4fancontrol are here <https://github.com/Ps3itaTeam/ps4fancontrol>, to get the configuration to apply after reboot you need to run `ps4fancontrol --no-gui`, either by hand or with systemd. PSXITA didn't put their systemd service in their repository, and I haven't used systemd in years, so I sadly can't help you there.

**Comment by gabriel-maxx** [comment]
@Richard-Rogalski thanks it worked
